version: '3.9'

services:
  app:
    image: client_spotify # Nombre deseado para tu imagen
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/src 
      - ./tsconfig.json:/usr/src/tsconfig.json
